name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.2.0
